name: FANCE
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _tflow_select=2.1.0=gpu
  - backports=1.0=py_2
  - backports.weakref=1.0.post1=py_1
  - blas=1.0=mkl
  - c-ares=1.15.0=h7b6447c_1001
  - ca-certificates=2019.5.15=1
  - cairo=1.14.12=h8948797_3
  - certifi=2019.6.16=py27_1
  - cudatoolkit=10.1.168=0
  - cudnn=7.6.0=cuda10.1_0
  - cupti=10.1.168=0
  - expat=2.2.6=he6710b0_0
  - fontconfig=2.13.0=h9420a91_0
  - freetype=2.9.1=h8a8886c_1
  - fribidi=1.0.5=h7b6447c_0
  - future=0.17.1=py27_0
  - glib=2.56.2=hd408876_0
  - google-pasta=0.1.7=py_0
  - graphite2=1.3.13=h23475e2_0
  - graphviz=2.40.1=h21bd128_2
  - h5py=2.9.0=py27h7918eee_0
  - harfbuzz=1.8.8=hffaf4a1_0
  - hdf5=1.10.4=hb1b8bf9_0
  - icu=58.2=h9c2bf20_1
  - intel-openmp=2019.4=243
  - jpeg=9b=h024ee3a_2
  - keras-applications=1.0.8=py_0
  - keras-base=2.2.4=py27_0
  - keras-preprocessing=1.1.0=py_1
  - libedit=3.1.20181209=hc058e9b_0
  - libffi=3.2.1=hd88cf55_4
  - libgcc-ng=9.1.0=hdf63c60_0
  - libgfortran-ng=7.3.0=hdf63c60_0
  - libgpuarray=0.7.6=h14c3975_0
  - libpng=1.6.37=hbc83047_0
  - libprotobuf=3.8.0=hd408876_0
  - libstdcxx-ng=9.1.0=hdf63c60_0
  - libtiff=4.0.10=h2733197_2
  - libuuid=1.0.3=h1bed415_2
  - libxcb=1.13=h1bed415_1
  - libxml2=2.9.9=hea5a465_1
  - linecache2=1.0.0=py27_0
  - mako=1.1.0=py_0
  - markdown=3.1.1=py27_0
  - markupsafe=1.1.1=py27h14c3975_0
  - mkl=2019.4=243
  - mkl-service=2.0.2=py27h7b6447c_0
  - mkl_fft=1.0.14=py27ha843d7b_0
  - mkl_random=1.0.2=py27hd81dba3_0
  - mock=3.0.5=py27_0
  - ncurses=6.1=he6710b0_1
  - numpy-base=1.16.4=py27hde5b4d6_0
  - openssl=1.1.1c=h7b6447c_1
  - pango=1.42.4=h049681c_0
  - pcre=8.43=he6710b0_0
  - pixman=0.38.0=h7b6447c_0
  - pygpu=0.7.6=py27h3010b51_1000
  - python=2.7.16=h9bab390_0
  - readline=7.0=h7b6447c_5
  - setuptools=41.0.1=py27_0
  - sqlite=3.29.0=h7b6447c_0
  - tensorboard=1.14.0=py27hf484d3e_0
  - tensorflow=1.14.0=gpu_py27h39f1c70_0
  - tensorflow-base=1.14.0=gpu_py27he45bfe2_0
  - tensorflow-estimator=1.14.0=py_0
  - tensorflow-gpu=1.14.0=h0d30ee6_0
  - theano=1.0.3=py27hfc679d8_1
  - tk=8.6.8=hbc83047_0
  - toolchain=2.4.0=0
  - toolchain_c_linux-64=2.4.0=0
  - toolchain_cxx_linux-64=2.4.0=0
  - traceback2=1.4.0=py27_0
  - unittest2=1.1.0=py27_0
  - werkzeug=0.15.5=py_0
  - wheel=0.33.4=py27_0
  - wrapt=1.11.2=py27h7b6447c_0
  - xz=5.2.4=h14c3975_4
  - yaml=0.1.7=had09818_2
  - zlib=1.2.11=h7b6447c_3
  - zstd=1.3.7=h0b5b093_0
  - pip:
    - absl-py==0.7.1
    - astor==0.8.0
    - backports-functools-lru-cache==1.5
    - backports-weakref==1.0.post1
    - beautifulsoup4==4.7.1
    - bs4==0.0.1
    - cycler==0.10.0
    - enum34==1.1.6
    - funcsigs==1.0.2
    - futures==3.2.0
    - gast==0.2.2
    - grpcio==1.21.1
    - keras==2.2.4
    - kiwisolver==1.1.0
    - lxml==4.3.4
    - matplotlib==2.2.4
    - nltk==3.4.3
    - numpy==1.16.4
    - pandas==0.24.2
    - pillow==6.1.0
    - pip==19.2.2
    - protobuf==3.8.0
    - pydot==1.4.1
    - pyparsing==2.4.0
    - python-dateutil==2.8.0
    - pytz==2019.1
    - pyyaml==5.1.1
    - scikit-learn==0.20.3
    - scipy==1.2.2
    - singledispatch==3.4.0.3
    - six==1.12.0
    - sklearn==0.0
    - soupsieve==1.9.2
    - subprocess32==3.5.4
    - termcolor==1.1.0
    - wordcloud==1.5.0
prefix: /home/xxx/anaconda3/envs/FANCE
